services:
  # MySQL Database
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    command: "--innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    cap_add: [SYS_NICE]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vinhtanfarm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    container_name: redis
    image: redis:6.2.12-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vinhtanfarm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # RabbitMQ Message Broker
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vinhtanfarm-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - vinhtanfarm-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - vinhtanfarm-network

  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue
    ports:
      - "8080:8080"
    networks:
      - vinhtanfarm-network
      
networks:
  vinhtanfarm-network:
    driver: bridge
    external: true
    name: vinhtanfarm-shared-network

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  elasticsearch_data:
  postgres_data:
